Dz5 component page
js-tasks-ru/htmlcss-20220919_antonprotasow69 pull request #11
Opened 2022-10-03 00:56 UTC by antcek

на монике 27 дюймов под футером остаётся свободное пространство, должно ли так быть?

2022-10-03 00:57 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-03 07:02 UTC, GSemikozov requested changes

2022-10-03 07:02 UTC, GSemikozov commented on components/template/template.css
> +    max-height: 100%;
можно просто height: 100%;

2022-10-03 07:02 UTC, GSemikozov commented on components/template/template.css
> +.page__header {
хедер нужно вставить тот который у нас уже создан и используется на Главной, только с модификатором для фона. И то же самое для футера. А эти классы-элементы можно оставить как миксы, через которые добавляем grid-area

2022-10-03 07:02 UTC, GSemikozov commented on components/template/template.css
> +.page__main {
да, и тут аналогично

2022-10-03 07:02 UTC, GSemikozov commented on components/template/template.css
> +.menu {
меню это отдельный блок, оформляем как компонент

2022-10-03 07:02 UTC, GSemikozov commented on components/template/template.css
> +    padding-left: 165px;
это лишний паддинг, когда будем встраивать, то контейнер должен решить проблему общего центрирования

2022-10-03 07:02 UTC, GSemikozov commented on components/template/template.css
> +.component {
это тоже отдельный компонент

2022-10-03 07:02 UTC, GSemikozov commented on components/template/template.css
> +    height: 746px;
фиксировать не надо

2022-10-03 07:02 UTC, GSemikozov commented on components/template/template.css
> +    margin-right: 165px;
лишнее

2022-10-03 07:02 UTC, GSemikozov commented on components/template/template.css
> +    background-color: #FFFFFF;
можем использовать переменные

2022-10-03 07:02 UTC, GSemikozov commented on components/template/template.css
> +margin-left: 56px;
это вероятно будет задано на уровне общего блока, который формирует разметку для Меню и Компонента

2022-10-03 07:02 UTC, GSemikozov commented on components/template/template.css
> +.page__footer {
см выше

2022-10-03 11:00 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-03 11:07 UTC, antcek commented on components/template/template.css
> +    max-height: 100%;
+

2022-10-03 11:44 UTC, antcek commented on components/template/template.css
> +.page__header {
+

2022-10-03 12:16 UTC, antcek commented on components/template/template.css
> +.page__main {
поменял

2022-10-03 12:21 UTC, antcek commented on components/template/template.css
> +.menu {
сделал

2022-10-03 12:23 UTC, antcek commented on components/template/template.css
> +    padding-left: 165px;
убрал

2022-10-03 12:26 UTC, antcek commented on components/template/template.css
> +.component {
переместил

2022-10-03 12:26 UTC, antcek commented on components/template/template.css
> +    height: 746px;
убрал

2022-10-03 12:33 UTC, antcek commented on components/template/template.css
> +    margin-right: 165px;
убрал

2022-10-03 13:02 UTC, antcek commented on components/template/template.css
> +.page__footer {
поменял

2022-10-03 13:48 UTC, antcek commented on components/template/template.css
> +margin-left: 56px;
убрал

2022-10-03 13:58 UTC, antcek commented on components/template/template.css
> +    background-color: #FFFFFF;
добавил

2022-10-03 14:08 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-03 19:58 UTC, GSemikozov requested changes

2022-10-03 19:58 UTC, GSemikozov commented on components/template/template.css
> +.page__header_background {
header_bg_transparent на урвоне блока header

2022-10-03 19:58 UTC, GSemikozov commented on components/template/template.css
> +.page__footer_background {
footer_bg_transparent - на уровне блока footer

2022-10-03 19:58 UTC, GSemikozov commented on components/template/template.css
> +.footer__title {
элемент блока footer

2022-10-06 12:23 UTC, antcek commented on components/template/template.css
> +.footer__title {
изменил

2022-10-06 12:25 UTC, antcek commented on components/template/template.css
> +.page__footer_background {
переместил

2022-10-06 12:29 UTC, antcek commented on components/template/template.css
> +.page__header_background {
переместил

2022-10-06 20:08 UTC, GSemikozov requested changes

2022-10-06 20:08 UTC, GSemikozov commented on components/page/page.css
> +.header
не совсем понятно почему в блоке пэйдж на самом деле болтаются части хедера и футера)
стили хедера должны быть в файле стилей хедера, футера - в футере

2022-10-06 21:07 UTC, antcek commented on components/page/page.css
> +.header
сделал

2022-10-06 21:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-07 00:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-07 01:35 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-07 15:47 UTC, GSemikozov requested changes

2022-10-07 15:47 UTC, GSemikozov commented on components/card/card.css
> +        background-color: #FFFFFF;
те свойства которые не меняются незачем дублировать

2022-10-07 15:47 UTC, GSemikozov commented on components/card/card.css
> +        font-family: 'Inter';
и тут

2022-10-07 15:47 UTC, GSemikozov commented on components/container/container.css
> +.container_header {
для футера и хедера слишком специфические модификаторы - в будущем чтобы поменять поведение элементов в хедере придется лезть в другой компонент, а это нехорошо - это тот случай, когда отступы лучше разруливать на уровне тех компонентов, элементам которых они нужны

2022-10-07 15:47 UTC, GSemikozov commented on components/header/header.css
> +.page__header {
элемент блока пэйдж должен быть описан в файле этого блока, а не в хедере

2022-10-07 15:47 UTC, GSemikozov commented on components/preview/preview.css
> +.preview__border_bottom {
модификаторы всегда используются с тем, ЧТО они модифицируют, и никогда - самостоятельно. Здесь видимо речь об элементе

2022-10-07 15:47 UTC, GSemikozov commented on components/preview/preview.css
> +.preview__border_top {
см  ниже

2022-10-07 21:39 UTC, antcek commented on components/preview/preview.css
> +.preview__border_bottom {
подправил

2022-10-07 21:39 UTC, antcek commented on components/preview/preview.css
> +.preview__border_top {
подправил

2022-10-07 21:42 UTC, antcek commented on components/header/header.css
> +.page__header {
переместил

2022-10-07 22:13 UTC, antcek commented on components/container/container.css
> +.container_header {
поменял

2022-10-07 22:17 UTC, antcek commented on components/card/card.css
> +        background-color: #FFFFFF;
убрал

2022-10-07 22:17 UTC, antcek commented on components/card/card.css
> +        font-family: 'Inter';
убрал

2022-10-08 00:40 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-08 01:15 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-08 10:21 UTC, GSemikozov requested changes

2022-10-08 10:21 UTC, GSemikozov commented on components/preview/preview.css
> +.preview__border-top {
если у превью должны быть бордеры снизу и сверху - наверно удобнее задать сразу на блоке, и не создавать ради этого отдельные пустые элементы в разметке)

2022-10-08 22:15 UTC, antcek commented on components/preview/preview.css
> +.preview__border-top {
сделал)

2022-10-08 22:15 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-08 23:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-09 00:29 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-10 08:53 UTC, GSemikozov requested changes

2022-10-10 08:53 UTC, GSemikozov commented on components/page/page.css
> +.page__header {
всю разметку страницы оформлять через блок page не надо, здесь можно разместить только необходимые классы-миксы (например для задания grid-area встраиваемым блоком). А в остальном - внутренняя реализация компонентов типа хедер или футер описывается в файлых этих блоков

2022-10-10 12:27 UTC, antcek commented on components/page/page.css
> +.page__header {
переделал

2022-10-10 15:47 UTC, GSemikozov approved these changes

2022-10-10 15:47 UTC, merged