Calendar
js-tasks-ru/htmlcss-20220919_antonprotasow69 pull request #12
Opened 2022-10-03 18:29 UTC by antcek

2022-10-03 18:29 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-03 19:59 UTC, GSemikozov requested changes

2022-10-03 19:59 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    padding-top: 28px;
padding: 28px 26px 32px

2022-10-03 19:59 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    opacity: 0,2;
`.`

2022-10-03 19:59 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    background-color: #4263EB;
не забываем использовать переменные

2022-10-03 20:44 UTC, antcek commented on 05-lection3/03-calendar/calendar.css
> +    padding-top: 28px;
добавил

2022-10-03 20:44 UTC, antcek commented on 05-lection3/03-calendar/calendar.css
> +    opacity: 0,2;
исправил

2022-10-03 20:46 UTC, antcek commented on 05-lection3/03-calendar/calendar.css
> +    background-color: #4263EB;
добавил

2022-10-05 08:16 UTC, GSemikozov approved these changes

2022-10-05 08:17 UTC, merged