Svg sprite
js-tasks-ru/htmlcss-20220919_antonprotasow69 pull request #18
Opened 2022-10-10 18:13 UTC by antcek

2022-10-10 18:14 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-12 11:05 UTC, GSemikozov requested changes

2022-10-12 11:05 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +        <link rel="stylesheet" href="../../assets/css/sprite.css">
нет необходимости это делать)

2022-10-12 12:55 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-12 12:55 UTC, antcek commented on 03-lection1/02-accordion/index.html
> +        <link rel="stylesheet" href="../../assets/css/sprite.css">
удалил

2022-10-12 20:43 UTC, GSemikozov approved these changes

2022-10-12 20:43 UTC, merged