Burger
js-tasks-ru/htmlcss-20220919_antonprotasow69 pull request #25
Opened 2022-10-15 18:38 UTC by antcek

2022-10-15 18:39 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-15 18:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-16 21:15 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-16 21:15 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-16 22:05 UTC, GSemikozov requested changes

2022-10-16 22:05 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-open {
кнопка открытия это не часть бургер-меню, удалим

2022-10-16 22:05 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-close {
.burger-menu__burger-close

2022-10-16 22:05 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +   .burger-open {
удалим

2022-10-16 22:22 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-16 22:31 UTC, antcek commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-open {
удалил

2022-10-16 22:33 UTC, antcek commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-open {
где тогда модифицировать эту кнопку?(убрать фон + бордер + сделать невидимой для десктопа)

2022-10-16 22:34 UTC, antcek commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-close {
сделал

2022-10-16 22:34 UTC, antcek commented on 09-lection7/01-burger-menu/burger-menu.css
> +   .burger-open {
удалил

2022-10-16 22:35 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-16 22:51 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-open {
если следовать макету и говорить о добавлении меню в хедер - то тогда это элемент хедера

2022-10-16 22:52 UTC, antcek commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-open {
принял

2022-10-16 22:59 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-17 19:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-18 09:02 UTC, GSemikozov approved these changes

2022-10-18 09:02 UTC, merged