Dz3 button fixed
js-tasks-ru/htmlcss-20220919_antonprotasow69 pull request #5
Opened 2022-09-27 18:07 UTC by antcek

оставил нужные стили для данного задания

2022-09-27 18:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-27 20:48 UTC, GSemikozov requested changes

2022-09-27 20:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  width: 189px;
жестко фиксировать ширину не надо, можно удалить

2022-09-27 20:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  display: inline;
как раз таки лучше inline-block

2022-09-27 20:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  width: 189px;
вместо этого лучше указать недостающие паддинги

2022-09-27 20:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    transition: opacity 200ms ease-in-out, background 200ms ease-in-out;
если транзишн общий у разных типов - то его лучше указать на уровне блока, а не модификатора

2022-09-27 20:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    transition: opacity 200ms ease-in-out, background 200ms ease-in-out;
и тут

2022-09-27 20:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    border-color: var(--alternate);
дублируем (уже указано выше)

2022-09-27 20:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    transition: opacity 200ms ease-in-out, background 200ms ease-in-out;
унести в класс блока

2022-09-27 20:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  cursor: pointer;
такой курсор можно выставить на кнопку по умолчанию

2022-09-27 20:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_primary_disabled:disabled
класс-модификатор здесь лишний, должно быть: .button:disabled

2022-09-27 20:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  cursor: not-allowed;
вместо такого курсора советую pointer-events: none

2022-09-27 20:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    color: #ffffff;
а цвет и прочее у disabled менять не надо, достаточно opacity

2022-09-27 20:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_secondary_disabled:disabled
отсюда и ниже можно удалить, поскольку disabled общий для всех типов кнопок

2022-09-28 21:22 UTC, GSemikozov requested changes

2022-09-28 21:22 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +{   display: flex;
тогда inline-flex (иначе кнопка растянется на всю ширину родителя)

2022-09-28 21:22 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  flex-basis: 10%;
лишнее

2022-09-28 21:22 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  border: 1px ;
лишний пробел после 1px

2022-09-28 21:22 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  margin: 1em 0.5em;
марджины на уровне блока не задаем

2022-09-28 21:22 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  margin: 1em 0.5em;
зато не хватает паддингов

2022-09-28 21:22 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
удалим (жесткое граничение не нужно)

2022-09-28 21:22 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding-left: 32px;
вместо одного паддинга слева надо указать паддинги со всех сторон, причем раз уж ниже указали марджин, который на уровне блока не указываем, то по всей видимости это должен быть элемент блока - то есть .accordion__item

2022-09-28 21:22 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +
остальные стили текста тоже можно указать)

2022-09-28 21:22 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> -<!DOCTYPE html>
нужно вернуть сюда разметку аккордиона

2022-09-29 20:10 UTC, GSemikozov requested changes

2022-09-29 20:10 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +{   margin: 0.5em;
марджины на уровне блока не задаем

2022-09-29 20:10 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +{ margin: 0.5em;
и тут

2022-09-29 20:10 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +{ margin: 0.5em;
и тут

2022-09-29 20:10 UTC, GSemikozov commented on 03-lection1/01-button/index.html
> +    <button class="button button_primary button_primary_disabled" disabled>Primary </button>
button_primary_disabled - лишний класс

2022-09-29 20:10 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +
вот здесь должен быть div с классом accordion

2022-09-29 20:10 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +        <details class="accordion" open>
а здесь - accordion__item

2022-09-29 20:10 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +            <summary class="accordion__summary accordion__item  ">
ну а здесь accordion__item не должно быть

2022-09-29 20:10 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-bottom: 8px;
на уровне блока марджины не задаем, надо на уровне accordion__item

2022-09-29 20:10 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    max-width: 730px;
лишнее ограничение

2022-09-29 20:10 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion:hover {
почему pointer только на hover? можно сразу на accordion__item

2022-09-29 20:10 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding-left: 32px;
паддинги общие лучше задать на accordion__item

2022-09-29 20:10 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding-left: 32px;
при accordion__item[open] важно обратить внимание что паддинг снизу будет больше

2022-09-29 20:10 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-bottom: 24px;
при правильной расстановке классом это видимо будет лишним

2022-09-29 20:10 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> + .accordion_content {
.accordion__content

2022-09-29 20:10 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +     padding: 0 48px 32px 32px;
если паддинги будут на уровне  .accordion__item, то здесь не надо

2022-09-29 20:10 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item_marker {
.accordion__marker

2022-09-29 20:10 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  details[open] .accordion__item_marker {
селекторы тегов в БЭМ не используем, .accordion__item[open] .accordion__marker

2022-09-29 20:24 UTC, antcek commented on 03-lection1/01-button/button.css
> +{   margin: 0.5em;
все подтёр

2022-09-29 20:24 UTC, antcek commented on 03-lection1/01-button/index.html
> +    <button class="button button_primary button_primary_disabled" disabled>Primary </button>
убрал

2022-09-29 20:31 UTC, antcek commented on 03-lection1/02-accordion/index.html
> +
добавил

2022-09-29 20:31 UTC, antcek commented on 03-lection1/02-accordion/index.html
> +        <details class="accordion" open>
поменял

2022-09-29 20:32 UTC, antcek commented on 03-lection1/02-accordion/index.html
> +            <summary class="accordion__summary accordion__item  ">
подтёр

2022-09-29 20:34 UTC, antcek commented on 03-lection1/02-accordion/accordion.css
> +    margin-bottom: 8px;
марджин убрал

2022-09-29 20:37 UTC, antcek commented on 03-lection1/02-accordion/accordion.css
> +    max-width: 730px;
убрал

2022-09-29 20:40 UTC, antcek commented on 03-lection1/02-accordion/accordion.css
> +.accordion:hover {
изменил

2022-09-29 20:44 UTC, antcek commented on 03-lection1/02-accordion/accordion.css
> +  details[open] .accordion__item_marker {
есть

2022-09-29 21:00 UTC, antcek commented on 03-lection1/02-accordion/accordion.css
> +    padding-left: 32px;
задал

2022-09-29 21:04 UTC, antcek commented on 03-lection1/02-accordion/accordion.css
> +    margin-bottom: 24px;
убрал

2022-09-29 21:05 UTC, antcek commented on 03-lection1/02-accordion/accordion.css
> + .accordion_content {
исправил

2022-09-29 21:10 UTC, antcek commented on 03-lection1/02-accordion/accordion.css
> +     padding: 0 48px 32px 32px;
оставил верхний и нижний( что б был отступ от 'Accordion item' и от нижней границы, иначе сжимает

2022-09-29 21:21 UTC, antcek commented on 03-lection1/02-accordion/accordion.css
> +     padding: 0 48px 32px 32px;
убрал

2022-09-29 21:21 UTC, antcek commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item_marker {
заменил

2022-09-30 08:11 UTC, GSemikozov requested changes

2022-09-30 08:11 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  padding-left: 4rem;
паддинги уже ведь на уровне блока заданы - надо удалить отсюда)

2022-09-30 08:11 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    box-sizing: border-box ;
все стили из этого класса надо перенести в .accordion__item

2022-09-30 08:11 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion_marker {
.accordion__marker

2022-09-30 08:11 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item[open] .accordion_marker {
.accordion__marker

2022-09-30 10:58 UTC, antcek commented on 03-lection1/02-accordion/accordion.css
> +.accordion_marker {
добавил _

2022-09-30 10:58 UTC, antcek commented on 03-lection1/02-accordion/accordion.css
> +    box-sizing: border-box ;
перенёс

2022-09-30 10:58 UTC, antcek commented on 03-lection1/01-button/button.css
> +  padding-left: 4rem;
удалил

2022-09-30 14:30 UTC, antcek commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item[open] .accordion_marker {
изменил

2022-09-30 15:50 UTC, GSemikozov approved these changes

2022-09-30 15:51 UTC, merged