added cards on main page
js-tasks-ru/htmlcss-20220919_antonprotasow69 pull request #8
Opened 2022-10-01 14:09 UTC by antcek

2022-10-01 14:09 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-02 19:28 UTC, GSemikozov requested changes

2022-10-02 19:28 UTC, GSemikozov commented on components/preview/preview.css
> +.preview__card {
.preview__cards

2022-10-02 19:28 UTC, GSemikozov commented on components/preview/preview.css
> +.card {
нужно унести в отдельную папку и в отдельный файл

2022-10-02 19:41 UTC, antcek commented on components/preview/preview.css
> +.preview__card {
заменил

2022-10-02 20:50 UTC, GSemikozov approved these changes

2022-10-02 20:50 UTC, merged